name = "app"
version = "1.0.0"

[dependencies]
argv = ">= 1.0.2 and < 2.0.0"
booklet = ">= 1.1.0 and < 2.0.0"
contour = ">= 1.2.1 and < 2.0.0"
ewe = ">= 2.1.1 and < 3.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
frontmatter = ">= 1.0.1 and < 2.0.0"
glailglind = ">= 2.2.0 and < 3.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_time = ">= 1.6.0 and < 2.0.0"
group_registry = ">= 1.0.0 and < 2.0.0"
jot = ">= 8.0.0 and < 9.0.0"
just = ">= 2.1.0 and < 3.0.0"
lustre = ">= 5.4.0 and < 6.0.0"
polly = ">= 3.0.0 and < 4.0.0"
simplifile = ">= 2.3.2 and < 3.0.0"
tom = ">= 2.0.0 and < 3.0.0"
